name: Test Formula

on:
  push:
    paths:
      - 'Formula/**'
  pull_request:
    paths:
      - 'Formula/**'

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6

      - name: brew tap
        run: brew tap kiro-generator/kiro-generator https://github.com/kiro-generator/homebrew-kiro-generator

      - name: brew audit
        run: brew audit --strict kiro-generator/kiro-generator/kiro-generator

      - name: brew install
        run: brew install --verbose kiro-generator/kiro-generator/kiro-generator

      - name: brew test
        run: brew test kiro-generator/kiro-generator/kiro-generator
